name: ape_fund_me

dependencies:
  - name: chainlink
    github: smartcontractkit/chainlink-brownie-contracts
    version: 1.1.1  # compatible con v0.8

solidity:
  version: 0.8.19
  import_remapping:
    - "@chainlink=chainlink"

dotenv: .env

plugins:
  - name: solidity
  - name: ethereum
  - name: foundry

default_ecosystem: ethereum

ethereum:
  local:
    default_provider: foundry
  sepolia:
    default_provider: node
    verify: true
    eth_usd_price_feed: '0x694AA1769357215DE4FAC081bf1f309aDC325306'
  mainnet-fork:
    default_provider: foundry
    eth_usd_price_feed: '0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419'

foundry:
  fork:
    ethereum:
      mainnet:
        upstream_provider: node
      sepolia:
        upstream_provider: node

node:
  ethereum:
    sepolia:
      uri: https://mainnet.infura.io/v3/967864a8a40b40aca8384cf067734c7e

etherscan:
  api_key: ${ETHERSCAN_API_KEY}

test:
  balance: 10000 ether
  mnemonic: test test test test test test test test test test test junk
